config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root to: "pages#home"

  resources :movies, only: [:index, :show] do
    post "/intentions" => "intentions#create"
    delete "/intentions" => "intentions#destroy"
  end

  resources :users, only: [:show]
  get '/friends' => "users#friends"

end

app/models/intention.rb
class Intention < ActiveRecord::Base
  belongs_to :users
  belongs_to :movies

end

app/models/movie.rb
class Movie < ActiveRecord::Base
  has_many :users, through: :intentions


  def self.get_new_movies
    request = Typhoeus::Request.new(URI.escape("http://api.themoviedb.org/3/movie/upcoming"), method: :get, params: { api_key: "9980989d70b0f176b38dcf207cfe4a04" },headers: { Accept: "application/json" }
)
    request.run
    response = request.response.body
    response = JSON.parse(response)
    results = response["results"]
    results.each do |movie|
      unless Movie.exists?(themoviedb_id = movie["id"])
        Movie.create(title: movie["title"], themoviedb_id: movie["id"], original_language: movie["original_language"], overview: movie["overview"], poster_path: movie["poster_path"], release_date: movie["release_date"])
      end
    end
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  serialize :friends
  has_many :movies, through: :intentions

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :registerable, and :timeoutable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]

  after_create :send_welcome_email

  def send_welcome_email
    UserMailer.welcome_email(self).deliver_now
  end

  def get_friends
    request = Typhoeus::Request.new(
    URI.escape("https://graph.facebook.com/v2.5/me/friends"),
    method: :get,
    params: { access_token: self.facebook_token },
    )
    request.run
    response = JSON.parse(request.response.body)
    my_friends = []
    response["data"].to_a.each do |friend|
      my_friends << friend["id"].delete("^0-9")
    end
      self.update_attribute(:friends, my_friends)
  end

  def get_user_attributes
  request = Typhoeus::Request.new(
    URI.escape("https://graph.facebook.com/v2.5/me/"),
    method: :get,
    params: { access_token: self.facebook_token, fields: "first_name,last_name" },
    )
    request.run
    response = JSON.parse(request.response.body)
    self.update_attributes(:first_name => response["first_name"], :last_name => response["last_name"])
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create! do |user|
      user.email = auth["info"]["email"]
      user.image = auth["info"]["image"]
      user.facebook_token = auth["credentials"]["token"]
      user.password = Devise.friendly_token[0,20]
    end
  end

  def full_name
    [first_name, last_name].join(" ")
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/intentions_controller.rb
class IntentionsController < ApplicationController

  def create
    intention = Intention.where(:user_id => params[:user_id], :movie_id => params[:movie_id])
    unless intention.exists?
      Intention.create(:user_id => params[:user_id], :movie_id => params[:movie_id])
    end
    redirect_to movie_path(params[:movie_id])
  end

  def destroy
    intention = Intention.where(user_id: params[:user_id], movie_id: params[:movie_id]).first
    if intention
      Intention.delete(intention.id)
    end
    redirect_to movie_path(params[:movie_id])
  end

private

  def intention_params
    params.require(:intention).permit(:user_id, :movie_id)
  end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

before_action :authenticate_user!

  def index
    @movies = Movie.where(release_date: (Date.today-10..Date.today+10))
    render "index"
  end

  def show
    @movie = Movie.find(params[:id])
    intentions = Intention.where(:movie_id => params[:id])
    user_ids = []
    intentions.each do |intention|
      user_ids << intention.user_id
    end
    @users = User.where(id: user_ids, uid: current_user.friends)
    render "show"
  end

private
  def movie_params
    params.require(:movie).permit(:title, :themoviedb_id, :original_language, :overview, :release_date, :poster_path)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    render "home"
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])
    @user.get_user_attributes
    @user.get_friends
    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to movies_path
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    if current_user.friends.include?(@user.uid) || @user == current_user
      my_intentions = Intention.where(:user_id => params[:id])
      movie_ids = []
      my_intentions.each do |intention|
        movie_ids << intention[:movie_id]
      end
      @movies = Movie.where(release_date: (Date.today-10..Date.today+10), id: movie_ids)
      render "show"
    else
      render "not_a_friend"
    end
  end

before_action :authenticate_user!

  def friends
    @friends = User.where(uid: current_user.friends)
    render "friends"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/intentions_helper.rb
module IntentionsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html lang="en">
  <head>
    <title>See It</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

  </head>
  <body>
    <%= render 'nav_partials/navbar' %>
    <div class = "container">

      <%= yield %>

    </div>
  </body>
</html>

app/views/movies/index.html.erb
<% @movies.each do |movie| %>
<%= link_to movie.title, movie_path(movie) %><br />
<% end %>

app/views/movies/show.html.erb
<h1><%= @movie.title %></h1>
<strong>Release date:</strong> <%= @movie.release_date %>

<% unless Intention.where(:user_id => current_user.id, :movie_id => @movie.id).exists? %>
<h2>Want to see this movie?</h2>
<p><%= link_to "Add Movie", movie_intentions_path(:user_id => current_user.id, :movie_id => @movie.id), method:"POST" %></p>
<% else %>
<p>You already want to see this movie.</p>
<p><%= link_to "Remove Movie", movie_intentions_path(:user_id => current_user.id, :movie_id => @movie.id), method: "DELETE" %>
<% end %>

<h2>Friends</h2>
<% if @users.empty? %>
  <p>No friends to see this movie yet.</p>
<% else %>
  <% @users.each do |user| %>
    <div class="user-block">
      <%= image_tag(user.image, class: "user-image") %>
      <%= link_to user.full_name, user_path(user) %>
    </div>
  <% end %>
<% end %>

app/views/nav_partials/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <%= link_to "See It", root_path, class: "navbar-brand" %>
    </div>

      <ul class="nav navbar-nav">
        <li><%= link_to "Movies", movies_path %></li>
        <li><%= link_to "Friends", friends_path %></li>
        <% if current_user %>
          <li><%= link_to "Me", user_path(current_user) %></li>
        <% end %>
      </ul>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <% unless current_user %><%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook), role: "button" %>
<% else %><%= link_to "Log Out", destroy_user_session_path, method:'DELETE', role: "button" %><% end %>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/pages/home.html.erb
<h1>Home</h1>
<p>Hello.</p>

<% if current_user %>
  <h2>You're logged in!</h2>
<% end %>

app/views/users/friends.html.erb
<h1>My Friends</h1>
<p><%= pluralize(@friends.count, 'friend is', 'friends are') %> using See It.</p>
<p>Check out what movies they want to see:</p>
<% @friends.each do |friend| %>
  <div class="user-block">
    <%= image_tag(friend.image, class: "user-image") %>
    <%= link_to friend.full_name, user_path(friend) %>
  </div>
<% end %>

app/views/users/not_a_friend.html.erb
<h1><%= @user.full_name %></h1>
<p>Sorry, it looks like <%= @user.first_name %> isn't your friend on Facebook.</p>

<p>If you and <%= @user.first_name %> recently became Facebook friends, please <%= link_to "log out", destroy_user_session_path, method:'DELETE' %> of See It and then log back in again.</p>

app/views/users/show.html.erb
<%= image_tag(@user.image, class: "user_image") %>
<h1><%= @user.full_name %></h1>
<h2>Upcoming Movies I Want to See</h2>

<% if @movies.empty? %>
<p>This person hasn't picked any movies to see yet.<p>
<% end %>
<% @movies.each do |movie| %>
  <p><%= link_to movie.title, movie_path(movie) %></p>
<% end %>